version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.12-management
    ports:
      - 5672:5672
      - 15672:15672

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: ${DATABASE_URL}
      RMQ_URL: ${RMQ_URL}
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - rabbitmq

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app

volumes:
  pg-data:
